WebApp/Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class InfoController : Controller
    {
        public ActionResult Prices()
        {
            return View();
        }

        public ActionResult Informations()
        {
            return View();
        }

        public ActionResult FAQ()
        {
            return View();
        }
    }
}

WebApp/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Config;
using WebApp.Data;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class ReservationController : Controller
    {
        [HttpGet]  
        public ActionResult Index()
        {
            ViewBag.Termini = Repo.GetSlobodniTermini(DateTime.Today, 1);
            ViewBag.Trajanja = Repo.GetTrajanja();
            ViewBag.Datum = DateTime.Parse(DateTime.UtcNow.ToShortDateString());
            return View();
        }

        [HttpPost]
        public ActionResult Index(Rezervacija rezervacija)
        {
            Repo.AddRezervacija(rezervacija);
            return RedirectToAction("View", new { id = rezervacija.RezervacijaId, added = true });
        }

        [HttpGet]
        public ActionResult View(Guid id)
        {
            using (var db = new TennisContext())
            {
                var x = db.Rezervacijas.SingleOrDefault(b => b.RezervacijaId == id);
                return View(x);
            }
        }

        [HttpGet]
        public ActionResult Book()
        {
            if (!bool.Parse(ConfigClass.GetProperty("active")))
            {
                return RedirectToAction("Unavailable");
            }
            ViewBag.Termini = Repo.GetSlobodniTermini(DateTime.UtcNow, 1);
            ViewBag.Trajanja = Repo.GetTrajanja();
            ViewBag.Datum = DateTime.Parse(DateTime.UtcNow.ToShortDateString());
            ViewBag.DoWeDeletePersonalData = bool.Parse(ConfigClass.GetProperty("doWeDeletePersonalData"));
            return View();
        }
        
        [HttpGet]
        public ActionResult AddNotes(Guid id)
        {
            ViewBag.ReservationId = id;
            var _reservation = Repo.GetRezervacija(id);
            if(!String.IsNullOrEmpty(_reservation.Notes))
            {
                ViewBag.Notes = _reservation.Notes;
            }
            return View();
        }

        [HttpPost]
        public ActionResult AddNotes(Guid guid, String Notes)
        {
            var _reservation = Repo.GetRezervacija(guid);
            _reservation.Notes = Notes;
            Repo.UpdateReservation(_reservation, guid);
            return RedirectToAction("View", new { id = guid });
        }

        public ActionResult Unavailable()
        {
            return View();
        }

        public JsonResult GetActive()
        {
            return Json(ConfigClass.GetProperty("active"), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Book(Rezervacija rezervacija)
        {
            Repo.AddRezervacija(rezervacija);
            return RedirectToAction("View", new { id = rezervacija.RezervacijaId });
        }

        public ActionResult Cancel(Guid id)
        {
            var rezervacija = Repo.GetRezervacija(id);
            Repo.OtkaziRezervaciju(rezervacija);
            return RedirectToAction(nameof(Deleted), new { id });
        }
        
        public ActionResult Deleted(Guid id)
        {
            ViewBag.Id = id;
            return View();
        }

        public ActionResult GetSlobodniTermini(DateTime date)
        {
            return Json(Repo.GetSlobodniTermini(date, 1), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetSlobodniTereni(DateTime date, int time)
        {
            return Json(Repo.GetSlobodniTereni(date, time), JsonRequestBehavior.AllowGet);
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
@using System.Configuration;
@using WebApp.Data;
@using WebApp.Config;
@using WebApp.Controllers;
<!DOCTYPE html>
<html>
<head>
    <meta name="theme-color" content="#333">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - @ConfigClass.GetProperty("appShortName")</title>
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Cinzel|Courgette|Dancing+Script|Gloria+Hallelujah|Permanent+Marker" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="font-family: 'Quicksand', Helvetica, sans-serif; font-size: 1.7em; padding: 0; opacity: 0;" class="container">
    <div id="body-container">
        <div class="navbar navbar-inverse navbar-fixed-top container">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink(ConfigClass.GetProperty("appShortName"), "Index", "Home", new { area = "" }, new { @class = "navbar-brand navbar-link", id = "pocetnaLink" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Book now", nameof(ReservationController.Book), "Reservation", null, new { @class= "navbar-link" })</li>
                        <li>@Html.ActionLink("Informations", nameof(InfoController.Informations), "Info", null, new { @class = "navbar-link" })</li>
                        <li>@Html.ActionLink("Prices", nameof(InfoController.Prices), "Info", null, new { @class = "navbar-link" })</li>
                        <li>@Html.ActionLink("FAQ", nameof(InfoController.FAQ), "Info", null, new { @class = "navbar-link" })</li>

                        @if (User.IsInRole("Admin") || User.IsInRole("Moderator"))
                        {
                            <li>@Html.ActionLink("Admin panel", nameof(AdminController.Panel), "Admin")</li>
                        }
                    </ul>
                    <div style="padding-right: 40px;">
                        @Html.Partial("_LoginPartial")

                    </div>

                </div>
            </div>
        </div>
        <div id="custom-header">
            <div class="container slided" style="text-align: center; font-family: 'Cinzel', serif; font-size: 1.2em; background-image: url('../../Images/tennis-bg.jpg'); background-size: cover;">
                <row>
                    <div class="col-md-12">
                        <img id="header-img" style="margin: auto; margin-top: 57px;" class="img" src="~/Images/logo5.png" /> @**@
                    </div>
                    <div class="col-md-12" id="titleHolder">
                        @ConfigClass.GetProperty("appLongName")
                    </div>
                </row>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
        </div>

        <br />
        <br />
        <br />
        <div class="container">
            <div class="col-md-12">
                <hr />
                <footer style="text-align: center; font-size: 0.8em;">
                    <div style="float: left; display: inline-block;">
                        <p style="font-size: 1.28em;">&copy; @DateTime.Now.Year - @ConfigClass.GetProperty("appShortName")</p>
                    </div>
                    <div style="float: right;">
                        @Html.Partial("_SocialIcons")
                    </div>
                </footer>
            </div>
        </div>
    </div>
</body>
</html>

<style>
    .highlight {
        font-weight: bold;
        color: red;
    }

    #custom-header {
        font-size: 2.5em;
        color: #fff;
        text-shadow: rgba(0,0,0,0.8) 0 0 6px;
        background-color: #fff;
        width: 100%;
        margin-bottom: 1px;
        -moz-box-shadow: rgba(0,0,0,0.3) 0 0 5px;
        -webkit-box-shadow: rgba(0,0,0,0.3) 0 0 5px;
        box-shadow: rgba(0,0,0,0.3) 0 0 5px;
    }


    @@media only screen and (max-width: 600px) {
        #header-img {
            width: 200px;
        }

        #titleHolder{
            font-size: 2.7rem;
        }
    }

    @@media only screen and (min-width: 600px){
        body {
            margin-top: 10px;
            background-image: url("../../Images/Backgrounds/@ConfigClass.GetProperty("slikaPozadineSadrzaja")");
            background-attachment: fixed;
        }

        #header-img {
            width: 320px;
        }

        #body-container {
            -moz-box-shadow: 0 0 6px rgba(0, 0, 0, 0.3);
            -webkit-box-shadow: 0 0 6px rgba(0, 0, 0, 0.3);
            box-shadow: 0 0 6px rgba(0, 0, 0, 0.3);
            background-color: white;
            border-radius: 10px;
            margin-bottom: 10px;
        }
    }

    #body-container {
        backgroud-color: #fff;
    background-image: url("../../Images/Backgrounds/cream_dust.png");
    }
</style>

<style>
    #titleHolder {
        text-shadow: 0px 0px 7px #000;
    }
</style>

<script>
    $(document).ready(function () {
        $("body").fadeTo(180, 1);
        $(".slided").slideDown();

        var str = location.href.toLowerCase();
        $(".navbar-link").each(function () {
            if (str.indexOf(this.href.toLowerCase()) > -1) {
                $("navbar-link.highlight").removeClass("highlight");
                $(this).addClass("highlight");
            }
        });
    });

</script> 

WebApp/Views/Shared/_SocialIcons.cshtml
<p id="socialHolder" style="font-size: 2em; margin-top: -5px;">
    <a href="http://facebook.com/" style="color: #3b5998;">
        <i class="fab fa-facebook-square"></i>
    </a>
    <a href="http://instagram.com/" style="color: #ee3c3c;">
        <i class="fab fa-instagram"></i>
    </a>
</p>

<style>
    #socialHolder > a:hover{
        text-decoration: none;
    }
</style>